[package]
name = "suma-cve-audit-tool"
version = "0.4.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["cve-audit-types", "cve-audit-ui"]

[dependencies]
log = "0.4.*"
rust-embed = "6.4.*"
serde_derive = "1.0.*"
serde = "1.0.*"
warp = "0.3.*"
mime_guess = "2.0.*"
reqwest = "0.11.*"
iso8601 = "0.6.*"
chrono = "0.4.*"
toml = "0.7.*"
serde_json = "1.0.*"
bincode = "1.3.*"
hifitime = "3.8.*"
pretty_env_logger = "0.4.*"
once_cell = "1.17.*"
futures = "0.3.*"
config = "0.13.1"
lazy_static = "1.4"

[dependencies.tokio]
version = "1.25.*"
features = ["full"]

[dependencies.sqlx]
version = "0.6.*"
features = ["sqlite","runtime-tokio-native-tls"]

[dependencies.cve-audit-types]
version = "0.5.*"
path = "./cve-audit-types"

[dependencies.xmlrpc]
version = "0.15.*"