[package]
name = "suma-cve-audit-tool"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["cve-audit-types", "cve-audit-ui"]

[dependencies]
log = "0.4.*"
rust-embed = "6.3.*"
serde_derive = "1.0.*"
serde = "1.0.*"
warp = "0.3.*"
mime_guess = "2.0.*"
reqwest = "0.11.*"
iso8601 = "0.4.*"
chrono = "0.4.*"
toml = "0.5.*"
serde_json = "1.0.*"
sled = "0.34.*"
bincode = "1.3.*"
hifitime = "2.3.*"
pretty_env_logger = "0.4.*"

[dependencies.tokio]
version = "1.17.*"
features = ["rt-multi-thread"]

[dependencies.rusqlite]
version = "0.26.*"
features = ["bundled"]

[dependencies.cve-audit-types]
version = "0.1.0"
path = "./cve-audit-types"

[dependencies.xmlrpc]
version = "0.16.*"
path = "/Users/pascal/Repos/xmlrpc-rs"