[package]
name = "suma-cve-audit-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["cve-audit-types", "cve-audit-ui"]

[dependencies]
log = "0.4.14"
rust-embed = "6.3.0"
serde_derive = "1.0.*"
serde = "1.0.*"
warp = "0.3.2"
mime_guess = "2.0.3"

[dependencies.tokio]
version = "1.16.*"
features = ["full"]

[dependencies.cve-audit-types]
version = "0.1.0"
path = "./cve-audit-types"
