[package]
name = "suma-cve-audit-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["cve-audit-types", "cve-audit-ui"]

[dependencies]
log = "0.4.14"
rust-embed = "6.3.*"
serde_derive = "1.0.*"
serde = "1.0.*"
warp = "0.3.*"
mime_guess = "2.0.*"
reqwest = "0.11.*"
xmlrpc = "0.15.*"
iso8601 = "0.4.1"
chrono = "0.4.19"
toml = "0.5.8"
serde_json = "1.0.79"
sled = "0.34.7"
bincode = "1.3.3"
hifitime = "2.3.2"

[dependencies.tokio]
version = "1.16.*"
features = ["full"]

[dependencies.sqlx]
version = "0.5.*"
features = ["sqlite", "runtime-tokio-native-tls" ]

[dependencies.rusqlite]
version = "0.26.3"
features = ["bundled"]

[dependencies.cve-audit-types]
version = "0.1.0"
path = "./cve-audit-types"
