[default.database]
folder = "./db/"

[default.suma]
url = "https://www.google.ch/rpc/api"
user = "rpc-user"
password = "secret"

[default.frontend]
listen = "127.0.0.1:8081"

[default.backend]
listen = "127.0.0.1:8090"