[package]
name = "cve-audit-ui"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.*"
serde = "1.0.*"
serde_derive = "1.0.*"
serde_json = "1.0.*"
wasm-bindgen = "0.2.*"
yew = "0.19.*"
yew-router = "0.16.0"
cve-audit-types = { version = "0.2.*", path = "../cve-audit-types" }
reqwasm = "0.4.*"
wasm-bindgen-futures = "0.4.*"
wasm-logger = "0.2.0"
log = "0.4.14"
yew-hooks = "0.1.46"
reqwest = "0.11.10"
