[package]
name = "cve-audit-ui"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.*"
serde = "1.0.*"
serde_derive = "1.0.*"
serde_json = "1.0.*"
yew = "0.19.*"
yew-router = "0.16.*"
cve-audit-types = { version = "0.3.*", path = "../cve-audit-types" }
reqwasm = "0.5.*"
wasm-bindgen-futures = "0.4.*"
wasm-logger = "0.2.*"
log = "0.4.*"
yew-hooks = "0.1.*"

[dependencies.web-sys]
version = "0.3.*"
features = ["FormData", "HtmlFormElement", "Request"]

[dependencies.wasm-bindgen]
version = "0.2.*"

[dependencies.reqwest]
version = "0.11.*"
features = ["json"]