name: CVE Audit Tool Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]
      include:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - os: windows-latest
          target: x86_64-pc-windows-gnu
  runs-on: ${{ matrix.os }}
  env:
    RUSTTARGET: ${{ matrix.target }}
  steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup & Update Rust Toolchain
        run: rustup update stable && rustup default stable && rustup target add ${{ matrix.target }}
      - name: Build Commons
        run: make build-commons
      - name: Build Web Components
        run: make build-web
      - name: Build Backend
        run: make build-backend
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/suma_cve_audit_tool($|.exe)
